update

diff --git a/coq/Makefile b/coq/Makefile
--- a/coq/Makefile
+++ b/coq/Makefile
@@ -1,3 +1,7 @@
+WARN_MSG = "(* !!! WARNING: AUTO GENERATED. DO NOT MODIFY !!! *)\n"
+
+OTT_LOC    = ../spec
+
 ## Name of the submakefile generated by coq_makefile
 COQMKFILENAME=CoqSrc.mk
 
@@ -23,10 +27,36 @@ coq: $(COQMKFILENAME) $(VFILES)
 %.vo: %.v
 	@$(MAKE) -f CoqSrc.mk $*.vo
 
+
+$(SYNTAX)_ott.v: $(OTT_LOC)/*.ott Makefile
+	ott $(OTT_LOC)/*.ott -o $(SYNTAX)_ott.v -coq_lngen true
+	make METALIB.FIX_$(SYNTAX)_ott
+	@if grep '<<no parses (' $@ >/dev/null 2>&1 && \
+		[ -z "$(DONTSTOP)" ]; then \
+			echo; \
+			echo "***** OTT PARSE ERROR(S) *****"; \
+			grep -n '<<no parses (' $@; \
+			$(RM) $@; \
+			exit 1; \
+	fi >&2
+
+
+$(TARGET)_inf.v: $(OTT_LOC)/*.ott Makefile
+	lngen --coq $(TARGET)_inf.v --coq-ott $(SYNTAX)_ott $(OTT_LOC)/$(TARGET).ott
+	make METALIB.FIX_$(TARGET)_inf
+
+
 $(COQMKFILENAME): Makefile $(shell ls *.v | grep -v _ott.v | grep -v _inf.v)
 	{ echo "-R . $(LIBNAME)" ; ls *.v ; } > _CoqProject && coq_makefile -arg '-w -variable-collision,-meta-collision,-require-in-module' -f _CoqProject -o $(COQMKFILENAME)
 
+METALIB.FIX_%:
+	sed -i -e 's/Metatheory/Metalib.Metatheory/g' $*.v
+	sed -i -e 's/LibLNgen/Metalib.LibLNgen/g' $*.v
+	sed '1d' $*.v > __TMP__; mv __TMP__ $*.v
+	@perl -pi -e 'print $(WARN_MSG) if $$. == 1' $*.v
+
+
 coqclean:
-	rm -if *.v-e *.v.d *.vio *.vo *.glob $(VOFILES) $(COQMKFILENAME)
+	rm -if *.v-e *.v.d *.vo *.glob $(VOFILES) $(COQMKFILENAME)
 
 clean: coqclean
